### ISSUE TITLE
Webm breaks through burger menu in mobile mode

### ISSUE THREAD

**Issue by lewri** [CorsixTH/corsixth.github.io#1]
The new sites menu in mobile mode doesn't seem to stop interaction with the content behind it. As a result, clicking where the video is can cause it to overlay.
![Screenshot_20210807-000956](https://user-images.githubusercontent.com/20030128/128579414-27d8e024-3b21-425d-9744-580a1755c8e7.jpg)

**Comment by lewri** [comment]
Did another check. Its just Chrome (and probably by extension chromium) doing it. Firefox behaves

**Comment by rmnvgr** [comment]
It should be fixed, at least it appears to be in Chromium dev tools. As I don't have an Android phone, could you check it?
